### PR TITLE
Add LUNA_DEV_ROOT develop var, --stack-root, prepend stack bin to PATH

### PR DESCRIPTION
**Pull request by binary132**
Needed for luna-studio bootstrap fix (to remove relative paths.)

I haven't tested this yet, will test once my local stack issues are resolved.

### CODE REVIEW

**Comment by mikusp** [comment]
I think that if you have a reproducible bug, that is fixed by setting up another stack root, it's an issue in stack. Duplicating stack root does not seem like a good idea to me, cause you end up with double the amount of disk space used.

**Comment by binary132** [comment]
Chatted with @wdanilo about this the other day, I'll revise to only include a `--stack-yaml` parameter in Stack commands instead so it can load the `extra-libs-path` (or whatever the parameter is...)

**Comment by binary132** [comment]
Additionally, I'm still struggling with syntax here so it will be a bit of time before I have it fully touched up.

**Comment by mikusp** [comment]
Please ask if you have any questions, we'll help as much as we can

18 lut 2018 21:20 "Bodie Solomon" <notifications@github.com> napisał(a):

Additionally, I'm still struggling with syntax here so it will be a bit of
time before I have it fully touched up.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/luna/luna-manager/pull/162#issuecomment-366544373>, or mute
the thread

**Pull request closed without merging**
